[Setting]
prefs_path              = /home/shved/.config/spotify/prefs
current_theme           = Gruvbox
inject_css              = 1
replace_colors          = 1
spotify_launch_flags    = 
spotify_path            = /opt/spotify
color_scheme            = dark
check_spicetify_upgrade = 0
overwrite_assets        = 1

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
experimental_features = 1
extensions            = adblock.js
custom_apps           = 
sidebar_config        = 1
home_config           = 1

[Patch]
xpui.js_find_8008 = ,(\\w+=)32,
xpui.js_repl_8008 = ,\${1}58,'

; DO NOT CHANGE!
[Backup]
version = 1.1.84.716.gc5f8b819
with    = 2.15.0
