[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[colors.primary]
background = '#212121'
# background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[cursor]
blink_interval	  = 400
unfocused_hollow  = false

[cursor.style]
blinking = "Always"
shape	 = "Block"

[font]
size = 10.5

[font.bold]
family = "JetBrains Mono"
style  = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style  = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style  = "Italic"

[font.normal]
family = "JetBrains Mono"
style  = "Regular"

[scrolling]
history		= 1000
multiplier  = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
dynamic_title	= false
opacity			= 1
startup_mode	= "Windowed"
padding         = { x = 10, y = 10 }
