include-file    = ~/.config/polybar/themes/gruvbox.ini

;==========================================================

[bar/eDP]
monitor         = eDP
width           = 100%              
height          = 24pt              
dpi             = 85

background      = ${colors.background}

line-size       = 2pt               
border-size     = 0pt
padding-left    = 0
padding-right   = 0
module-margin   = 0
separator       = " " 
; tray-position   = right
; tray-maxsize    = 12
; tray-padding    = 5

cursor-click    = pointer
cursor-scroll   = ns-resize
enable-ipc      = true
wm-restack      = bspwm

font-0          = SourceCodePro:size=14
font-1          = FontAwesome6Free:style=solid:size=13
font-2          = FontAwesome6Brands:style=solid:size=13
font-3          = FontAwesome6Pro:style=solid:size=13
font-4          = NotoSansCJKJP:size=14
font-5          = SymbolsNerdFontMono:style=2048-em

modules-left    = powermenu xwindow spotify
modules-center  = bspwm
modules-right   = battery xkeyboard wlan downspeed date 


[bar/HDMI]
monitor         = HDMI-A-0
width           = 100%              
height          = 24pt              
dpi             = 60

background      = ${colors.background}

line-size       = 2pt               
border-size     = 0pt
padding-left    = 0
padding-right   = 0
module-margin   = 0
separator       = " " 
tray-position   = right
tray-maxsize    = 12
tray-padding    = 5

cursor-click    = pointer
cursor-scroll   = ns-resize
enable-ipc      = true
wm-restack      = bspwm

font-0          = SourceCodePro:size=14
font-1          = FontAwesome6Free:style=solid:size=13
font-2          = FontAwesome6Brands:style=solid:size=13
font-3          = FontAwesome6Pro:style=solid:size=13
font-4          = NotoSansCJKJP:size=14
font-5          = SymbolsNerdFontMono:style=2048-em

modules-left    = powermenu xwindow 
modules-center  = bspwm
modules-right   = xkeyboard wlan downspeed date 

; ==========================================================

[module/battery]
type                            = internal/battery
battery                         = BAT0
interval                        = 1

label-full                      = "  %percentage%% "
label-low                       = "  %percentage%% "
label-discharging               = "  %percentage%% " 
label-charging                  = "  %percentage%% " 

format-charging-foreground      = ${colors.foreground}

label-low-foreground            = ${colors.foreground}

label-full-foreground           = ${colors.foreground}
label-discharging-foreground    = ${colors.foreground}

label-full-underline            = ${colors.blue}
label-low-underline             = ${colors.red}
label-discharging-underline     = ${colors.blue}
label-charging-underline        = ${colors.blue}

; ==========================================================

[module/bspwm]
type                        = internal/bspwm

label-focused               = %icon%
label-focused-underline     = ${colors.blue}
label-focused-foreground    = ${colors.blue}
label-focused-background    = ${colors.dark-gray}
label-focused-padding       = 2

label-occupied = %icon%
label-occupied-padding      = 2

label-urgent                = %icon%
label-urgent-background     = ${colors.red}
label-urgent-foreground     = ${colors.background}
label-urgent-padding        = 2

label-empty                 = %icon% 
label-empty-foreground      = ${colors.gray}
label-empty-padding         = 2

; ws-icon-0 = I;1
; ws-icon-1 = II;2 
; ws-icon-2 = III;3
; ws-icon-3 = IV;4
; ws-icon-4 = V;5
; ws-icon-5 = VI;6
; ws-icon-6 = VII;7
; ws-icon-7 = VIII;8
; ws-icon-8 = IX;9
; ws-icon-9 = X;10

ws-icon-0 = I; 
ws-icon-1 = II; 
ws-icon-2 = III; 
ws-icon-3 = IV;
ws-icon-4 = V; 
ws-icon-5 = VI; 
ws-icon-6 = VII; 
ws-icon-7 = VIII; 
ws-icon-8 = IX; 
ws-icon-9 = X; 

; ==========================================================

[module/date]
type                = internal/date
interval            = 1.0

label               = %time%
time                = " 🕓 %H:%M "
time-alt            = "  %A %d.%m.%y "

label-foreground    = ${colors.foreground}
format-underline    = ${colors.blue}

; ==========================================================

[module/spotify]
type            = custom/ipc
hook-0          = echo ""
hook-1          = spotifyctl -q status --format " |  %artist% - %title%"

[module/previous]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo "|  "
click-left = "spotifyctl -q previous"

[module/next]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo " |"
click-left = "spotifyctl -q next"

[module/playpause]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo " "
hook-2 = echo " "
click-left = "spotifyctl -q playpause"

; ==========================================================

[module/wlan]
type                            = internal/network
interface-type                  = wireless
label-connected                 = "  %essid% " 
label-disconnected              = "  Disconnected "

label-connected-foreground      = ${colors.foreground}
label-disconnected-foreground   = ${colors.foreground}

label-connected-underline       = ${colors.blue}
label-disconnected-underline    = ${colors.red}

[module/downspeed]
type                            = internal/network
interface-type                  = wireless
label-connected                 = "  %downspeed% "
label-connected-foreground      = ${colors.foreground}
label-connected-underline       = ${colors.blue}

; ==========================================================

[module/xkeyboard]
type                            = internal/xkeyboard
blacklist-0                     = num lock

label-layout                    = "  %layout% "
label-indicator-on              = " Caps lock "

label-layout-foreground         = ${colors.foreground}
label-indicator-on-foreground   = ${colors.foreground}

label-layout-underline          = ${colors.blue}
label-indicator-on-underline    = ${colors.yellow}

; ==========================================================

[module/xxxwindow]
type                = custom/script
interval            = 1
exec                = "sh $HOME/.local/bin/polybar/window-indicator.sh"

; ==========================================================

[module/powermenu]
type                = custom/text
click-left          = "sh $HOME/.config/rofi/launchers/powermenu/launch.sh"
content             = "  "
content-underline   = ${colors.powermenu}
content-padding     = 1

; ==========================================================

[module/xwindow]
type                = internal/xwindow
label               = %title%
label-empty         = Desktop
label-maxlen        = 61

; ==========================================================
;  
[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
