
animations              = true;
animation-stiffness     = 320;
animation-window-mass   = 0.4;
animation-clamping      = false;
# animation-dampening     = 21;

# [ zoom / slide-up / slide-down / slide-left/ slide-right /  none ]
# animation-for-open-window           = "zoom";
# animation-for-menu-window           = "slide-down";
# animation-for-unmap-window          = "slide-down";
# animation-for-transient-window      = "slide-down";
# animation-for-workspace-switch-in   = "slide-down";
# animation-for-workspace-switch-out  = "slide-up";

shadow                      = false;                     
shadow-radius               = 20;                       
shadow-opacity              = .55;                      
shadow-offset-x             = -10;                      
shadow-offset-y             = -5;                       
shadow-color                = "#000000";                

fading                      = true;                     
fade-delta                  = 17;                       
fade-in-step                = 0.10;                     
fade-out-step               = 0.10;                     
no-fading-openclose         = false;                    
no-fading-destroyed-argb    = false;                    

active-opacity              = 1;                        
inactive-opacity            = 1;                        
frame-opacity               = 1;                        
inactive-opacity-override   = false;                     
inactive-dim                = 0.25;                     

blur-method                 = "dual_kawase";
blur-strength               = 8;
blur-background             = true;                     
blur-background-fixed       = true;                     

corner-radius               = 0;

backend                     = "glx";
vsync                       = true;
log-level                   = "warn";
log-file                    = "/tmp/picom.log";

focus-exclude = [
    "class_g = 'Rofi'"
];              

opacity-rule = [
    # "85:class_g = 'Alacritty'       && focused",
    # "70:class_g = 'Alacritty'       && !focused",
    # "85:class_g = 'TelegramDesktop' && focused",
    # "85:class_g = 'TelegramDesktop' && !focused",
    "85:class_g = 'qBittorrent'     && focused",
    # "90:class_g = 'qBittorrent'     && !focused",
    # "80:class_g = 'Polybar'",
    # "85:class_g = 'Zathura'         && focused",
    # "95:class_g = 'Zathura'         && !focused",
    "90:class_g = 'Spotify'",
    # "85:class_g = 'Thunar'          && focused",
    # "85:class_g = 'Thunar'          && !focused",
    # "70:class_g = 'dunst'           && focused",
    # "70:class_g = 'Rofi'",
    # "90:class_g = 'Code'            && focused",
    # "95:class_g = 'Code'            && !focused",
];

rounded-corners-exclude = [
    "class_g     = 'Dunst'",
    "window_type = 'dock'",
    "window_type = 'desktop'",

];

blur-background-exclude = [
    "window_type = 'desktop'",
    "window_type = 'tooltip'",
    "window_type = 'utility'",
    "_GTK_FRAME_EXTENTS@:c",
];

shadow-exclude = [
    "_GTK_FRAME_EXTENTS@:c",
    "class_g = 'slop'",
];

wintypes: 
{
  dropdown_menu = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  notification  = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  popup_menu    = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  utility       = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  tooltip       = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  toolbar       = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  dialog        = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  dock          = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  menu          = { opacity = 1; shadow = false; full-shadow = false; fade = false }
  dnd           = { opacity = 1; shadow = false; full-shadow = false; fade = false }
}

# vim:ft=bash
